### ISSUE TITLE
May I get my data stored in the old sqlfiddle back?

### ISSUE THREAD

**Issue by sl-wxx** [zzzprojects/sqlfiddle4#1]
I use this link http://sqlfiddle.com/#!9/974ff5/6, may I get my data back?

**Comment by JonathanMagnan** [comment]
Hello @sl-wxx ,

We indeed have a backup of the old sqlfiddle database.

I will check this week if we can make it happen very soon.

Best Regards,

Jon

**Comment by tpetry** [comment]
I have created and shared many fiddles in the past too that do no longer. Having these URLs be working again would be awesome!

**Comment by JonathanMagnan** [comment]
It's coming very soon this week. However, the latest backup failed, so, unfortunately, we will lose a few weeks of data.

**Comment by JonathanMagnan** [comment]
Hello @sl-wxx , @tpetry 

It should now be possible to access legacy fiddle. I have tested multiple URLs, and they work correctly.

@sl-wxx Unfortunately, your link doesn't work. Is it possible it was created after November 9, 2023? Due to a mistake, we have 2 months worth of data that are lost forever. Let me know if you are 100% sure it was created before. I will try to double-check in this case.

Let me know @tpetry  on your side if your URL works again.

Best Regards,

Jon

**Comment by tpetry** [comment]
Works again. Thanks ❤️
