### ISSUE TITLE
Feature Proposing: online API or IDE plugin for unit tests

### ISSUE THREAD

**Issue by odys-z** [zzzprojects/sqlfiddle4#3]
I have some modules for generating SQL statements. To verify the results on variaous DB, I have to maintance different RDBMS. It's not practicable for some enterprise systems. If there are client/plugins for testing my results online, by running unit tests, say, 
    mvn test
it can be awesome.

Regards

BTW, it's typical for developers first try their SQL results, by hand, before integrate the data handling modules into the applications.

**Comment by JonathanMagnan** [comment]
Hello @odys-z ,

I recommend you to check for some already existing API such as: https://onecompiler.com/apis/code-execution

Under the hood, we are now using this API for the moment as it is way more stable than the previous service we were offering.

Best Regards,

Jon

**Comment by odys-z** [comment]
Hi @JonathanMagnan ,

Thank you for the help!

In the document you are directing,  there is no free try plan for "your_access_token"?

Another question is that to run unit tests etc., there should be some extension for the API, if I am correct.  Is the OneCompiler's server side open source?

E.g. The escape sequence for the REST API looks warkward, at least at the first sight. I'd like to find some way that can send JSON over http with semantics support at client side, whick will have IDE pop up hints while editing code. 

Best Regards,

Ody

BTW, what's you've done is amazing. The online studio looks like a variant of VS Code. Can you direct me where is the resource to do this?

**Comment by JonathanMagnan** [comment]
I'm not using through Rapid API, but I believe you have 1000 calls for free here: https://rapidapi.com/onecompiler-onecompiler-default/api/onecompiler-apis/pricing

Otherwise it's still very cheap (5$ for 10,000 call per month).

> Is the OneCompiler's server side open source?

OneCompiler is not open source.

> E.g. The escape sequence for the REST API looks warkward, at least at the first sight. I'd like to find some way that can send JSON over http with semantics support at client side, whick will have IDE pop up hints while editing code.

The API is really easy to use (at least when using C#). So far, it has always been very stable on my side. The major problem was to parse the output to create an `HTML` table from it.

If you need some code, I will be happy to share what I used but unfortunately my time is currently very limited, so I will not be able to help you much with it.

> BTW, what's you've done is amazing. The online studio looks like a variant of VS Code. Can you direct me where is the resource to do this?

Well, it's self-made so I'm not sure what you are asking here hehe

Best Regards,

Jon

**Comment by odys-z** [comment]
Nice work. I will come back for furthure questions.
Thank you!

**Comment by odys-z** [comment]
Hi Jon,

Thank you for your kind sharing source of OneCompiler. I am considering
implementing a Maven plugin for unit tests based on your API. But I am not
sure if there is any bandwidth for this. Anyway, thank you very much!

Best regards

Ody.
