### ISSUE TITLE
Request to update the MariaDB version

### ISSUE THREAD

**Issue by grooverdan** [zzzprojects/sqlfiddle4#5]
https://sqlfiddle.com/mariadb/online-compiler?id=6063d831-4270-4dab-bd46-1b34d4c239c5

The current version 10.7.8 is EOL and was [released 1.5 years ago](https://mariadb.com/kb/en/release-notes-mariadb-10-7-series/).

If a [long term support](https://mariadb.org/about/#maintenance-policy) is desired there is 11.4, but otherwise there is a 11.6 release available with a few more features including those from 11.5.

Happy to advise if you have any difficulty upgrading.

**Comment by JonathanMagnan** [comment]
Hello @grooverdan ,

We are no longer hosting the server for MariaDB. We are simply using/paying for the [OneCompiler](https://onecompiler.com/mariadb/42qrv9txj) API and provide an interface.

I will leave this issue open as we will ask him if he can upgrade at the beginning of 2025 if that is not already done. We currently prefer not to ask for it at this moment since we have already asked for quite some support/help from them recently, but we will surely ask for it in 3 months if nothing has been done.

If you wish, you can directly contact them: https://onecompiler.com/contact

Let me know if that answer correctly to your question.
Best Regards,

Jon

**Comment by grooverdan** [comment]
Perfectly understandable. Thanks for the background and links. I did do a direct contact.

**Comment by grooverdan** [comment]
updated. 11.4 there.

https://sqlfiddle.com/mariadb/online-compiler?id=fa8bdbe8-f49b-4bc0-97c2-64c3e1748c2c

Thanks for your help.

**Comment by JonathanMagnan** [comment]
Awesome ;)

Thank you for making it happen.

I added to my yearly recurring task to ask him once a year (early January) to update all database providers to the latest version.

Have a great week,

Best Regards,

Jon
